/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Modelo.Matricula;
import Modelo.PdfDAO;
import Modelo.PdfVO;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class Crea_Asig extends javax.swing.JFrame {

    Connection conex;
    String ruta_archivo;
    /**
     * Creates new form Crea_Asig
     */
    public Crea_Asig() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            this.setTitle("CREACIÓN DE ASIGNACIONES");
            transparente();
            Class.forName("com.mysql.jdbc.Driver");
            cargarmatricula(Matricula);
            setIconImage(getIconImage());
        } catch (ClassNotFoundException ex){
            Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return  retValue;
    }
    
    public void cargarmatricula(JComboBox matricula) {

        try {

            conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study", "root", "");

            String sql = "SELECT ID_Matricula, materia.Nombre, grupos.Nombre FROM matricula INNER JOIN materia ON matricula.ID_M = materia.ID_Materia INNER JOIN grupos ON matricula.ID_G = grupos.ID_Grupo";
            Statement st = conex.createStatement();
            ResultSet rs = st.executeQuery(sql);
            DefaultComboBoxModel model = new DefaultComboBoxModel();

            while (rs.next()) {
                
               model.addElement(new Matricula(rs.getInt("ID_Matricula"),rs.getString("materia.Nombre"),rs.getString("grupos.Nombre")));
            }
            matricula.setModel(model);
        } catch (SQLException e) {
            System.err.println(e);
        }

    }
    
    public void transparente(){
        Cerrar.setOpaque(false);
        Cerrar.setContentAreaFilled(false);
        Cerrar.setBorderPainted(false);
        Minimizar.setOpaque(false);
        Minimizar.setContentAreaFilled(false);
        Minimizar.setBorderPainted(false);
        Imagen.setOpaque(false);
        Imagen.setContentAreaFilled(false);
        Imagen.setBorderPainted(false);    
    }
    
    public void guardar_pdfA(int idAsignacion, String nombreE, File ruta) {
        PdfDAO pa = new PdfDAO();
        PdfVO po = new PdfVO();
        po.setIdEntrega(idAsignacion);
        po.setNombre(nombreE);
        try {
            byte[] pdf = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(pdf);
            po.setDocumento(pdf);
        } catch (IOException ex) {
            po.setDocumento(null);
            System.out.println("Error al agregar archivo pdf "+ex.getMessage());
        }
        pa.Agregar_PdfVOA(po,idAsignacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Imagen = new javax.swing.JButton();
        Salir = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Perfil = new javax.swing.JLabel();
        Clases = new javax.swing.JLabel();
        Salud = new javax.swing.JLabel();
        Clase = new javax.swing.JLabel();
        Materias = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        FechaCierre = new com.toedter.calendar.JDateChooser();
        Matricula = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        NomAsig = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        FechaInicio = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        Cod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Ruta = new javax.swing.JTextField();
        subir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Minimizar = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(168, 201, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen.png"))); // NOI18N
        Imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagenActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        Salir.setText("Cerrar sesión");
        Salir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SalirMouseMoved(evt);
            }
        });
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        Inicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        Inicio.setText("Inicio");
        Inicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                InicioMouseMoved(evt);
            }
        });
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InicioMouseExited(evt);
            }
        });
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, -1));

        Perfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        Perfil.setText("Perfil");
        Perfil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PerfilMouseMoved(evt);
            }
        });
        Perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PerfilMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PerfilMouseExited(evt);
            }
        });
        jPanel1.add(Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, -1));

        Clases.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estudiar.png"))); // NOI18N
        Clases.setText("Crear Asignación");
        Clases.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ClasesMouseMoved(evt);
            }
        });
        Clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClasesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClasesMouseExited(evt);
            }
        });
        jPanel1.add(Clases, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, -1));

        Salud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/corazon.png"))); // NOI18N
        Salud.setText("Salud/Deporte");
        Salud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SaludMouseMoved(evt);
            }
        });
        Salud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaludMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaludMouseExited(evt);
            }
        });
        jPanel1.add(Salud, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        Clase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/presentacion.png"))); // NOI18N
        Clase.setText("Crear materia");
        Clase.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ClaseMouseMoved(evt);
            }
        });
        Clase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClaseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClaseMouseExited(evt);
            }
        });
        jPanel1.add(Clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        Materias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Materias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/educacion.png"))); // NOI18N
        Materias.setText("Entregas");
        Materias.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MateriasMouseMoved(evt);
            }
        });
        Materias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MateriasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MateriasMouseExited(evt);
            }
        });
        jPanel1.add(Materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 560));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(143, 170, 220));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Creación de asignaciones");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel9)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 840, -1));

        FechaCierre.setDateFormatString("d/MM/yyyy HH:mm:ss");
        jPanel2.add(FechaCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 180, 30));

        jPanel2.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 180, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Profesor para crear una asignación llena los siguientes datos:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Nombre de la asignación:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("250 caracteres máximo");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Fecha y hora de inicio:");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Matricula:");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        NomAsig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(NomAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, -1));

        jButton3.setBackground(new java.awt.Color(143, 170, 220));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Crear.png"))); // NOI18N
        jButton3.setText("Crear asignación");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Descripción:");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        FechaInicio.setDateFormatString("d/MM/yyyy HH:mm:ss");
        jPanel2.add(FechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 180, 30));

        Descripcion.setColumns(20);
        Descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Descripcion.setLineWrap(true);
        Descripcion.setRows(5);
        jScrollPane1.setViewportView(Descripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 360, 140));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Código de la asignación:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        Cod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(Cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 120, -1));

        jButton1.setBackground(new java.awt.Color(168, 201, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 40, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Fecha y hora de cierre:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Nombre del archivo:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        Ruta.setEditable(false);
        jPanel2.add(Ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 230, -1));

        subir.setBackground(new java.awt.Color(143, 170, 220));
        subir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subir.setText("Subir archivo");
        subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirActionPerformed(evt);
            }
        });
        jPanel2.add(subir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        jButton2.setBackground(new java.awt.Color(168, 201, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 40, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 41, -1, 520));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarActionPerformed(evt);
            }
        });
        jPanel3.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 40));

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        jPanel3.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 40, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 840, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenActionPerformed

    }//GEN-LAST:event_ImagenActionPerformed

    private void SalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseMoved
        Salir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_SalirMouseMoved

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        this.setVisible(false);
        Final v= new Final();
        v.setVisible(true);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_SalirMouseExited

    private void InicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseMoved
        Inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_InicioMouseMoved

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        this.setVisible(false);
        Pag_PrinP v= new Pag_PrinP();
        v.setVisible(true);
    }//GEN-LAST:event_InicioMouseClicked

    private void InicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseExited
        Inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_InicioMouseExited

    private void PerfilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseMoved
        Perfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_PerfilMouseMoved

    private void PerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseClicked
        this.setVisible(false);
        PerfilP v= new PerfilP();
        v.setVisible(true);
    }//GEN-LAST:event_PerfilMouseClicked

    private void PerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseExited
        Perfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_PerfilMouseExited

    private void ClasesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClasesMouseMoved
        Clases.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_ClasesMouseMoved

    private void ClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClasesMouseClicked
        this.setVisible(false);
        Crea_Asig v= new Crea_Asig();
        v.setVisible(true);
    }//GEN-LAST:event_ClasesMouseClicked

    private void ClasesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClasesMouseExited
        Clases.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_ClasesMouseExited

    private void SaludMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaludMouseMoved
        Salud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_SaludMouseMoved

    private void SaludMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaludMouseClicked
        ResultSet resultado = null;
        int cod;
        String enfermedad;

        cod =Integer.parseInt(JOptionPane.showInputDialog("Digita tu código de profesor"));

        try{
            conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study","root","");
            Statement st=conex.createStatement();

            resultado=st.executeQuery("SELECT * FROM profesor  WHERE Codigo_Profe ="+cod);

            if (resultado.next()==true){ 
                enfermedad = resultado.getString("Enfermedad");                              
                if (enfermedad.equals("Diabetes")){
                    this.setVisible(false);
                    Diabetes_Profe e = new Diabetes_Profe();
                    e.setVisible(true);
                }else if (enfermedad.equals("Tiroides")){
                    this.setVisible(false);
                    Tiroides_Profe e = new Tiroides_Profe();
                    e.setVisible(true);
                }else if (enfermedad.equals("Hipertension")){
                    this.setVisible(false);
                    Hiperten_Profe e = new Hiperten_Profe();
                    e.setVisible(true);
                }else if (enfermedad.equals("No_aplica")){
                    this.setVisible(false);
                    Salud_Profe e = new Salud_Profe();
                    e.setVisible(true);
                } 
           }else if (resultado.next()==false){
               JOptionPane.showMessageDialog(null,"Código de profesor no existente");
           }
            st.close();
            conex.close();

        }catch (SQLException ex){
            Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_SaludMouseClicked

    private void SaludMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaludMouseExited
        Salud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_SaludMouseExited

    private void ClaseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaseMouseMoved
        Clase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_ClaseMouseMoved

    private void ClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaseMouseClicked
        this.setVisible(false);
        Crear_Mate v = new Crear_Mate();
        v.setVisible(true);
    }//GEN-LAST:event_ClaseMouseClicked

    private void ClaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaseMouseExited
        Clase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_ClaseMouseExited

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarActionPerformed
        this.setState (Pag_Principal.ICONIFIED);
    }//GEN-LAST:event_MinimizarActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void MateriasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriasMouseMoved
        Materias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_MateriasMouseMoved

    private void MateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriasMouseClicked
        this.setVisible(false);
        Entregas v= new Entregas();
        v.setVisible(true);
    }//GEN-LAST:event_MateriasMouseClicked

    private void MateriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriasMouseExited
        Materias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_MateriasMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Cod.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Debes llenar el campo de código");
       }else if (NomAsig.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Debes ponerle un nombre a tu asignación");
       }else if (FechaInicio.getCalendar().equals("")){
           JOptionPane.showMessageDialog(null, "Debes poner una fecha de inicio");
       }else if (FechaCierre.getCalendar().equals("")){
           JOptionPane.showMessageDialog(null, "Debes poner una fecha de cierre");
       }else if (Descripcion.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Debes poner una descripción");
       }else{
        int cod = Integer.parseInt(Cod.getText());
        
        String nom = NomAsig.getText();
        
        int Anio = FechaInicio.getCalendar().get(Calendar.YEAR);
        int Mes = FechaInicio.getCalendar().get(Calendar.MONTH);
        int Dia = FechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH);
        int Hora = FechaInicio.getCalendar().get(Calendar.HOUR);
        int Minutos = FechaInicio.getCalendar().get(Calendar.MINUTE);
        int Segundos = FechaInicio.getCalendar().get(Calendar.SECOND);
        
        String FechaInicio = ""+Anio+"-"+(Mes+1)+"-"+Dia+" "+Hora+":"+Minutos+":"+Segundos;
        
        int AnioC = FechaCierre.getCalendar().get(Calendar.YEAR);
        int MesC = FechaCierre.getCalendar().get(Calendar.MONTH);
        int DiaC = FechaCierre.getCalendar().get(Calendar.DAY_OF_MONTH);
        int HoraC = FechaCierre.getCalendar().get(Calendar.HOUR);
        int MinutosC = FechaCierre.getCalendar().get(Calendar.MINUTE);
        int SegundosC = FechaCierre.getCalendar().get(Calendar.SECOND);
        
        String FechaCierre = ""+AnioC+"-"+(MesC+1)+"-"+DiaC+" "+HoraC+":"+MinutosC+":"+SegundosC;
        
        
        Matricula matriculaSeleccionao = (Matricula) Matricula.getSelectedItem();
        
        try{
         File ruta = new File(ruta_archivo);
         conex=DriverManager.getConnection("jdbc:mysql://localhost/thats_study","root","");
         Statement st=conex.createStatement();
         st.executeUpdate("INSERT INTO asignacion (ID_Asig, Nombre, Descripcion, Fecha_Inicio, Fecha_Cierre, ID_Matricula) VALUES ('"+Cod.getText()+"','"+NomAsig.getText()+"','"+Descripcion.getText()+"','"+FechaInicio+"','"+FechaCierre+"','"+matriculaSeleccionao.getIdMatricula()+"')");
            guardar_pdfA(cod, nom, ruta);
         JOptionPane.showMessageDialog(null, "Asignación subida");
        }catch(SQLException ex){
         Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE,null,ex); 
         JOptionPane.showMessageDialog(null, "El código de la asignación ya existe, digita un código diferente");
        }
       }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null,"Si vas a subir un archivo asegurate que sea PDF, para que los estudiantes puedan visualizarlo");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirActionPerformed
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
        j.setFileFilter(fi);
        int se = j.showOpenDialog(this);
        if (se == 0) {
            this.Ruta.setText("" + j.getSelectedFile().getName());
            ruta_archivo = j.getSelectedFile().getAbsolutePath();
        } else {
        }
    }//GEN-LAST:event_subirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "El código lo crea el profesor puede ser 1 a 4 dígitos\nEsto se hace para que el proceso de calificación sea más fácil");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crea_Asig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crea_Asig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crea_Asig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crea_Asig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crea_Asig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JLabel Clase;
    private javax.swing.JLabel Clases;
    private javax.swing.JTextField Cod;
    private javax.swing.JTextArea Descripcion;
    private com.toedter.calendar.JDateChooser FechaCierre;
    private com.toedter.calendar.JDateChooser FechaInicio;
    private javax.swing.JButton Imagen;
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Materias;
    private javax.swing.JComboBox<String> Matricula;
    private javax.swing.JButton Minimizar;
    private javax.swing.JTextField NomAsig;
    private javax.swing.JLabel Perfil;
    private javax.swing.JTextField Ruta;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel Salud;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton subir;
    // End of variables declaration//GEN-END:variables
}
