/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Modelo.Profesor;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Crear_Mate extends javax.swing.JFrame {
    Connection conex;
    /**
     * Creates new form Crear_Clase
     */
    public Crear_Mate() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            this.setTitle("CREACIÓN DE GRUPOS");
            transparente();
            Class.forName("com.mysql.jdbc.Driver");
            cargargrupo(Docente);
        } catch (ClassNotFoundException ex){
            Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
       return retValue;
    }
    
    public void transparente(){
        Cerrar.setOpaque(false);
        Cerrar.setContentAreaFilled(false);
        Cerrar.setBorderPainted(false);
        Minimizar.setOpaque(false);
        Minimizar.setContentAreaFilled(false);
        Minimizar.setBorderPainted(false);
        Imagen.setOpaque(false);
        Imagen.setContentAreaFilled(false);
        Imagen.setBorderPainted(false);
        Crear.setOpaque(false);
        Crear.setContentAreaFilled(false);
        Crear.setBorderPainted(false);
        Visualizar.setOpaque(false);
        Visualizar.setContentAreaFilled(false);
        Visualizar.setBorderPainted(false);
        Eliminar.setOpaque(false);
        Eliminar.setContentAreaFilled(false);
        Eliminar.setBorderPainted(false);
        Limpiar.setOpaque(false);
        Limpiar.setContentAreaFilled(false);
        Limpiar.setBorderPainted(false);
        Actualizar.setOpaque(false);
        Actualizar.setContentAreaFilled(false);
        Actualizar.setBorderPainted(false);
        Buscar.setOpaque(false);
        Buscar.setContentAreaFilled(false);
        Buscar.setBorderPainted(false);
    
    }
    
    public void cargargrupo(JComboBox profesor) {

        try {

            conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study", "root", "");

            String sql = "SELECT codigo_profe, nombre,apellido FROM profesor";
            Statement st = conex.createStatement();
            ResultSet rs = st.executeQuery(sql);
            DefaultComboBoxModel model = new DefaultComboBoxModel();

            while (rs.next()) {
                
                model.addElement(new Profesor(rs.getInt("codigo_profe"),rs.getString("nombre"),rs.getString("apellido")));

            }
            profesor.setModel(model);
        } catch (SQLException e) {
            System.err.println(e);
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popborrar = new javax.swing.JPopupMenu();
        popeliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Imagen = new javax.swing.JButton();
        Salir = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Perfil = new javax.swing.JLabel();
        Salud = new javax.swing.JLabel();
        Clase = new javax.swing.JLabel();
        Clases = new javax.swing.JLabel();
        Materias = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Materias = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        codm = new javax.swing.JTextField();
        Crear = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Codigo_materia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nom_materia = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Docente = new javax.swing.JComboBox<>();
        Visualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Minimizar = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();

        popeliminar.setText("jMenuItem1");
        popborrar.add(popeliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(168, 201, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen.png"))); // NOI18N
        Imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagenActionPerformed(evt);
            }
        });
        jPanel1.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        Salir.setText("Cerrar sesión");
        Salir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SalirMouseMoved(evt);
            }
        });
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        Inicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        Inicio.setText("Inicio");
        Inicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                InicioMouseMoved(evt);
            }
        });
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InicioMouseExited(evt);
            }
        });
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, -1));

        Perfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        Perfil.setText("Perfil");
        Perfil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PerfilMouseMoved(evt);
            }
        });
        Perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PerfilMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PerfilMouseExited(evt);
            }
        });
        jPanel1.add(Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, -1));

        Salud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/corazon.png"))); // NOI18N
        Salud.setText("Salud/Deporte");
        Salud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SaludMouseMoved(evt);
            }
        });
        Salud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaludMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaludMouseExited(evt);
            }
        });
        jPanel1.add(Salud, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        Clase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/presentacion.png"))); // NOI18N
        Clase.setText("Crear materia");
        Clase.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ClaseMouseMoved(evt);
            }
        });
        Clase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClaseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClaseMouseExited(evt);
            }
        });
        jPanel1.add(Clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        Clases.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estudiar.png"))); // NOI18N
        Clases.setText("Crear Asignación");
        Clases.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ClasesMouseMoved(evt);
            }
        });
        Clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClasesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClasesMouseExited(evt);
            }
        });
        jPanel1.add(Clases, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, -1));

        Materias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Materias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/educacion.png"))); // NOI18N
        Materias.setText("Entregas");
        Materias.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MateriasMouseMoved(evt);
            }
        });
        Materias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MateriasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MateriasMouseExited(evt);
            }
        });
        jPanel1.add(Materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 560));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(143, 170, 220));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Creación de materias");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel9)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 840, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Si deseas crear una materia, añade los siguientes datos");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Nombre del docente:");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        Tabla_Materias.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Tabla_Materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID de materia", "Nombre de materia", "Nombre del docente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_Materias.setComponentPopupMenu(popborrar);
        Tabla_Materias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_MateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Materias);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 430, 270));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Materias creadas");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        Limpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 130, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Buscar:");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        codm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(codm, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 200, 30));

        Crear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Crear.png"))); // NOI18N
        Crear.setText("Crear Materia");
        Crear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        jPanel2.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 140, 50));

        Eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        Eliminar.setText("Eliminar ");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 150, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Nombre de la materia:");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Codigo_materia.setEditable(false);
        jPanel2.add(Codigo_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 160, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Código:");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        nom_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_materiaActionPerformed(evt);
            }
        });
        jPanel2.add(nom_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, 30));

        Buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel2.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, 50));

        Actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar.png"))); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 150, 50));

        jPanel2.add(Docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 160, 30));

        Visualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Visualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        Visualizar.setText("Visualizar");
        Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarActionPerformed(evt);
            }
        });
        jPanel2.add(Visualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 41, -1, 520));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarActionPerformed(evt);
            }
        });
        jPanel3.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 40));

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        jPanel3.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 40, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 840, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenActionPerformed

    }//GEN-LAST:event_ImagenActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarActionPerformed
        this.setState (Pag_Principal.ICONIFIED);
    }//GEN-LAST:event_MinimizarActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        if(nom_materia.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes darle un nombre a tu materia");
        }else{
        String nom = nom_materia.getText();
        Profesor docenteSeleccionao = (Profesor) Docente.getSelectedItem();
        
        try{
         conex=DriverManager.getConnection("jdbc:mysql://localhost/thats_study","root","");
         Statement st=conex.createStatement();
         st.executeUpdate ("INSERT INTO materia (Nombre, CodigoP) VALUES ('"+nom+"','"+docenteSeleccionao.getIdDocente()+"')");
         JOptionPane.showMessageDialog(null, "Hecho");
        }catch(SQLException ex){
        Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE,null,ex); 
        JOptionPane.showMessageDialog(null, "No es posible la conexión");
        }
        }
    }//GEN-LAST:event_CrearActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        if (nom_materia.getText().equals("")&& codm.getText().equals("")&&Codigo_materia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No hay datos que limpiar");
        }else{
        codm.setText("");
        nom_materia.setText("");
        Codigo_materia.setText("");
        }
    }//GEN-LAST:event_LimpiarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if (!codm.getText().equals("")){
        try{
           DefaultTableModel modelo=(DefaultTableModel)Tabla_Materias.getModel();
           int filas = modelo.getRowCount();
           for (int i = 0; i<filas; i++){
            modelo.removeRow(0);
           };
           conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study","root","");
           Statement st=conex.createStatement();
           
           String sqll = "SELECT ID_Materia, materia.Nombre, profesor.Nombre FROM materia INNER JOIN profesor ON materia.CodigoP = profesor.Codigo_Profe WHERE materia.ID_Materia='"+codm.getText()+"'OR materia.Nombre='"+codm.getText()+"'OR profesor.Nombre='"+codm.getText()+"'";
           ResultSet rs = st.executeQuery(sqll);
           rs.first();
           if(rs.first()== false){
               JOptionPane.showMessageDialog(null,"Materia o código no existente","ERROR",JOptionPane.ERROR_MESSAGE);
           }
           do{
               String [] fila={rs.getString(1),rs.getString(2),rs.getString(3)};
               modelo.addRow(fila);
           }while (rs.next());
           
        }catch (SQLException ex){
            Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE,null,ex);
            
        }
        }else{
            JOptionPane.showMessageDialog(null,"Ingresa código o nombre de la materia");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void Tabla_MateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_MateriasMouseClicked
        int fila=this.Tabla_Materias.getSelectedRow();
        
        this.Codigo_materia.setText(this.Tabla_Materias.getValueAt(fila, 0).toString());
        this.nom_materia.setText(this.Tabla_Materias.getValueAt(fila, 1).toString());
        String s = Tabla_Materias.getValueAt(Tabla_Materias.getSelectedRow(),2).toString(); 
        Object a = s; 
        Docente.setSelectedItem(a);
    }//GEN-LAST:event_Tabla_MateriasMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (Codigo_materia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selecciona una materia para eliminarla");
        }else{
        Statement st = null;
        try{
           conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study","root","");
           st=conex.createStatement();
           
           int datos =st.executeUpdate("DELETE FROM materia WHERE ID_Materia = '"+Codigo_materia.getText()+"'");
           JOptionPane.showMessageDialog(null,"Datos borrados");
           st.close();
           conex.close();
        }catch (SQLException ex){
            Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void SalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseMoved
        Salir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_SalirMouseMoved

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        this.setVisible(false);
        Final v= new Final();
        v.setVisible(true);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_SalirMouseExited

    private void InicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseMoved
        Inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_InicioMouseMoved

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        this.setVisible(false);
        Pag_PrinP v= new Pag_PrinP();
        v.setVisible(true);
    }//GEN-LAST:event_InicioMouseClicked

    private void InicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseExited
        Inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_InicioMouseExited

    private void PerfilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseMoved
        Perfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_PerfilMouseMoved

    private void PerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseClicked
        this.setVisible(false);
        PerfilP v= new PerfilP();
        v.setVisible(true);
    }//GEN-LAST:event_PerfilMouseClicked

    private void PerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseExited
        Perfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_PerfilMouseExited

    private void SaludMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaludMouseMoved
        Salud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_SaludMouseMoved

    private void SaludMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaludMouseClicked
        ResultSet resultado = null;
        int cod;
        String enfermedad;

        cod =Integer.parseInt(JOptionPane.showInputDialog("Digita tu código de profesor"));

        try{
            conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study","root","");
            Statement st=conex.createStatement();

            resultado=st.executeQuery("SELECT * FROM profesor  WHERE Codigo_Profe ="+cod);

            if (resultado.next()==true){ 
                enfermedad = resultado.getString("Enfermedad");                              
                if (enfermedad.equals("Diabetes")){
                    this.setVisible(false);
                    Diabetes_Profe e = new Diabetes_Profe();
                    e.setVisible(true);
                }else if (enfermedad.equals("Tiroides")){
                    this.setVisible(false);
                    Tiroides_Profe e = new Tiroides_Profe();
                    e.setVisible(true);
                }else if (enfermedad.equals("Hipertension")){
                    this.setVisible(false);
                    Hiperten_Profe e = new Hiperten_Profe();
                    e.setVisible(true);
                }else if (enfermedad.equals("No_aplica")){
                    this.setVisible(false);
                    Salud_Profe e = new Salud_Profe();
                    e.setVisible(true);
                } 
           }else if (resultado.next()==false){
               JOptionPane.showMessageDialog(null,"Código de profesor no existente");
           }
            st.close();
            conex.close();

        }catch (SQLException ex){
            Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_SaludMouseClicked

    private void SaludMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaludMouseExited
        Salud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_SaludMouseExited

    private void ClaseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaseMouseMoved
        Clase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_ClaseMouseMoved

    private void ClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaseMouseClicked
        this.setVisible(false);
        Crear_Mate v = new Crear_Mate();
        v.setVisible(true);
    }//GEN-LAST:event_ClaseMouseClicked

    private void ClaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaseMouseExited
        Clase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_ClaseMouseExited

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        if (Codigo_materia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debes elegir uno de los registros");
        }else if (nom_materia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debes llenar el campo de nombre del grupo");
        }else{
        String nom;
        
        nom=nom_materia.getText();
        Profesor docenteSeleccionao = (Profesor) Docente.getSelectedItem();
        
        Statement st = null;
        
        try{
           conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study","root","");
           st=conex.createStatement();
           
           int datos =st.executeUpdate("UPDATE materia SET Nombre ='"+nom+"',CodigoP = '"+docenteSeleccionao.getIdDocente()+"'WHERE ID_Materia = '"+Codigo_materia.getText()+"'");
           JOptionPane.showMessageDialog(null,"Datos actualizados");
           st.close();
           conex.close();
        }catch (SQLException ex){
            Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
    }//GEN-LAST:event_ActualizarActionPerformed

    private void VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarActionPerformed

        try{
            DefaultTableModel modelo=(DefaultTableModel)Tabla_Materias.getModel();
            int filas = modelo.getRowCount();
            for (int i = 0; i<filas; i++){
             modelo.removeRow(0);
            };
            conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study","root","");
            Statement st=conex.createStatement();

            String sqll = "SELECT ID_Materia, materia.Nombre, profesor.Nombre FROM materia INNER JOIN profesor ON materia.CodigoP = profesor.Codigo_Profe";
            ResultSet rs = st.executeQuery(sqll);
            rs.first();
            do{
                String [] fila={rs.getString(1),rs.getString(2),rs.getString(3)};
                modelo.addRow(fila);
            }while (rs.next());

        }catch (SQLException ex){
            Logger.getLogger(Crea_grupos.class.getName()).log(Level.SEVERE,null,ex);

        }

    }//GEN-LAST:event_VisualizarActionPerformed

    private void nom_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_materiaActionPerformed

    private void ClasesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClasesMouseMoved
        Clases.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_ClasesMouseMoved

    private void ClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClasesMouseClicked
        this.setVisible(false);
        Crea_Asig v= new Crea_Asig();
        v.setVisible(true);
    }//GEN-LAST:event_ClasesMouseClicked

    private void ClasesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClasesMouseExited
        Clases.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_ClasesMouseExited

    private void MateriasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriasMouseMoved
        Materias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143,170,220)));
    }//GEN-LAST:event_MateriasMouseMoved

    private void MateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriasMouseClicked
        this.setVisible(false);
        Entregas v= new Entregas();
        v.setVisible(true);
    }//GEN-LAST:event_MateriasMouseClicked

    private void MateriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriasMouseExited
        Materias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168,201,255)));
    }//GEN-LAST:event_MateriasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Mate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Mate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Mate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Mate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Mate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cerrar;
    private javax.swing.JLabel Clase;
    private javax.swing.JLabel Clases;
    private javax.swing.JTextField Codigo_materia;
    private javax.swing.JButton Crear;
    private javax.swing.JComboBox<String> Docente;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Imagen;
    private javax.swing.JLabel Inicio;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Materias;
    private javax.swing.JButton Minimizar;
    private javax.swing.JLabel Perfil;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel Salud;
    private javax.swing.JTable Tabla_Materias;
    private javax.swing.JButton Visualizar;
    private javax.swing.JTextField codm;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nom_materia;
    private javax.swing.JPopupMenu popborrar;
    private javax.swing.JMenuItem popeliminar;
    // End of variables declaration//GEN-END:variables

}
