/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Modelo.Grupo;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author User
 */
public class Registro_Estudiante extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    Connection conex;

    public Registro_Estudiante() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            this.setTitle("Registro de estudiante");
            botontransparente();
            textos();
            Class.forName("com.mysql.jdbc.Driver");
            cargargrupo(GrupoE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registro_Profesor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void textos() {
        TextPrompt a = new TextPrompt("Escribe tu código", CodigoE);
        TextPrompt b = new TextPrompt("1er nombre", nombre1);
        TextPrompt c = new TextPrompt("2do nombre", nombre2);
        TextPrompt d = new TextPrompt("1er apellido", apellido1);
        TextPrompt e = new TextPrompt("2do apellido", apellido2);
        TextPrompt g = new TextPrompt("Crea un usuario", UsuarioE);
        TextPrompt h = new TextPrompt("Crea una contraseña", ContraE);
        TextPrompt i = new TextPrompt("Digita tu correo electronico", Correo);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }

    public void botontransparente() {
        Cerrar.setOpaque(false);
        Cerrar.setContentAreaFilled(false);
        Cerrar.setBorderPainted(false);
        Minimizar.setOpaque(false);
        Minimizar.setContentAreaFilled(false);
        Minimizar.setBorderPainted(false);
        nombre1.setBackground(new java.awt.Color(0, 0, 0, 1));
        nombre2.setBackground(new java.awt.Color(0, 0, 0, 1));
        apellido1.setBackground(new java.awt.Color(0, 0, 0, 1));
        apellido2.setBackground(new java.awt.Color(0, 0, 0, 1));
        Correo.setBackground(new java.awt.Color(0, 0, 0, 1));
        fecha.setBackground(new java.awt.Color(0, 0, 0, 1));
        CodigoE.setBackground(new java.awt.Color(0, 0, 0, 1));
        UsuarioE.setBackground(new java.awt.Color(0, 0, 0, 1));
        ContraE.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    public void cargargrupo(JComboBox grupo) {

        try {

            conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study", "root", "");

            String sql = "SELECT id_grupo, nombre FROM grupos";
            Statement st = conex.createStatement();
            ResultSet rs = st.executeQuery(sql);
            DefaultComboBoxModel model = new DefaultComboBoxModel();

            while (rs.next()) {
                
                model.addElement(new Grupo(rs.getInt("id_grupo"),rs.getString("nombre")));

            }
            grupo.setModel(model);
        } catch (SQLException e) {
            System.err.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enfermedad = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JButton();
        Minimizar = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        apellido2 = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Hipertension = new javax.swing.JRadioButton();
        Diabetes = new javax.swing.JRadioButton();
        Latiroides = new javax.swing.JRadioButton();
        NoAplica = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        Masculino = new javax.swing.JRadioButton();
        Femenino = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CodigoE = new javax.swing.JTextField();
        UsuarioE = new javax.swing.JTextField();
        Comprobar = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        GrupoE = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        ContraE = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(1050, 575));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        Logo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoMouseMoved(evt);
            }
        });
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nombre.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel4.setText("Tu mejor sitio virtual para estudiar ");

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cerrar)
                    .addComponent(Minimizar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 110));

        jPanel4.setBackground(new java.awt.Color(218, 227, 243));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuidado-de-la-salud.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 40, 40));

        nombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre2.setBorder(null);
        jPanel4.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 180, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 40, 40));

        nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre1.setToolTipText("");
        nombre1.setBorder(null);
        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });
        jPanel4.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 180, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 40, 40));

        Correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Correo.setBorder(null);
        jPanel4.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 400, 30));

        apellido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apellido2.setBorder(null);
        jPanel4.add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 180, 30));
        jPanel4.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 180, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/correo-electronico.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 40, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 40, 40));

        Enfermedad.add(Hipertension);
        Hipertension.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hipertension.setText("Hipertensión ");
        jPanel4.add(Hipertension, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, -1));

        Enfermedad.add(Diabetes);
        Diabetes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Diabetes.setText("Diabetes");
        jPanel4.add(Diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        Enfermedad.add(Latiroides);
        Latiroides.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Latiroides.setText("Tiroides");
        jPanel4.add(Latiroides, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        Enfermedad.add(NoAplica);
        NoAplica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NoAplica.setText("N/A");
        NoAplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoAplicaActionPerformed(evt);
            }
        });
        jPanel4.add(NoAplica, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Sexo:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        Sexo.add(Masculino);
        Masculino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Masculino.setText("Masculino");
        jPanel4.add(Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        Sexo.add(Femenino);
        Femenino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Femenino.setText("Femenino");
        jPanel4.add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 220, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 220, 20));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 220, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 220, 20));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 440, 20));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 220, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("¿Sufres alguna de estas enfermedades?");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Selecciona tu grupo:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ESTUDIANTE INGRESA TU...");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        CodigoE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CodigoE.setBorder(null);
        CodigoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoEActionPerformed(evt);
            }
        });
        jPanel4.add(CodigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 160, 30));

        UsuarioE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsuarioE.setBorder(null);
        UsuarioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioEActionPerformed(evt);
            }
        });
        jPanel4.add(UsuarioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 190, 40));

        Comprobar.setBackground(new java.awt.Color(143, 170, 220));
        Comprobar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Comprobar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprobar.png"))); // NOI18N
        Comprobar.setText("COMPROBAR");
        Comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprobarActionPerformed(evt);
            }
        });
        jPanel4.add(Comprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        Iniciar.setBackground(new java.awt.Color(143, 170, 220));
        Iniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ordenador-portatil.png"))); // NOI18N
        Iniciar.setText("INICIAR SESIÓN");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        jPanel4.add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrar-contrasena.png"))); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 40, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contrasena.png"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 40, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipo.png"))); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 40, 40));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 40, 40));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 230, 10));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 10));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, 10));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 230, 10));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 40, 40));

        apellido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apellido1.setBorder(null);
        apellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido1ActionPerformed(evt);
            }
        });
        jPanel4.add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 30));

        jPanel4.add(GrupoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Fecha de nacimiento:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        ContraE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ContraE.setBorder(null);
        jPanel4.add(ContraE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 190, 40));

        scrollPane1.add(jPanel4);

        getContentPane().add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 730, 420));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro_total (1).png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarActionPerformed
        this.setState(Inicio.ICONIFIED);
    }//GEN-LAST:event_MinimizarActionPerformed

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        this.setVisible(false);
        Inicio v = new Inicio();
        v.setVisible(true);
    }//GEN-LAST:event_LogoMouseClicked

    private void LogoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseMoved
        Logo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_LogoMouseMoved

    private void LogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseExited
        Logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
    }//GEN-LAST:event_LogoMouseExited

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed

    }//GEN-LAST:event_nombre1ActionPerformed

    private void NoAplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoAplicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoAplicaActionPerformed

    private void CodigoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoEActionPerformed

    private void UsuarioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioEActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        this.setVisible(false);
        Cuenta_estudiante v = new Cuenta_estudiante();
        v.setVisible(true);
    }//GEN-LAST:event_IniciarActionPerformed

    private void ComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprobarActionPerformed
       
        if (nombre1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes poner un nombre");
        }
        
        if (apellido1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes poner un apellido");
        }
        
        if (fecha.getMaxSelectableDate().equals("")){
            JOptionPane.showMessageDialog(null,"Debes poner tu fecha de nacimiento");
        }
        
        if (CodigoE.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes poner tu código de estudiante");
        }
        
        if (UsuarioE.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes crear un usuario");
        }
        
        if (ContraE.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes crear una contraseña");
        }
        
        String Nom1 = nombre1.getText();
        String Nom2 = nombre2.getText();
        String Ape1 = apellido1.getText();
        String Ape2 = apellido2.getText();

        String Nombre = Nom1 + " " + Nom2;
        String Apellido = Ape1 + " " + Ape2;

        int Anio = fecha.getCalendar().get(Calendar.YEAR);
        int Mes = fecha.getCalendar().get(Calendar.MONTH);
        int Dia = fecha.getCalendar().get(Calendar.DAY_OF_MONTH);

        String FechaNac = "" + Anio + "-" + (Mes + 1) + "-" + Dia;

        String Enfermedad = null;

        if (Latiroides.isSelected()) {
            Enfermedad = "Tiroides";
        }
        if (Diabetes.isSelected()) {
            Enfermedad = "Diabetes";
        }
        if (Hipertension.isSelected()) {
            Enfermedad = "Hipertension";
        }
        if (NoAplica.isSelected()) {
            Enfermedad = "No_aplica";
        }

        String Email = Correo.getText();

        String Sexo = null;

        if (Femenino.isSelected()) {
            Sexo = "Femenino";
        }
        if (Masculino.isSelected()) {
            Sexo = "Masculino";
        }

        String Usuario = UsuarioE.getText();
        String Contra = ContraE.getText();

        String CodEstud = CodigoE.getText();

        Grupo grupoSeleccionao = (Grupo) GrupoE.getSelectedItem();

        try {
            conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study", "root", "");
            Statement st = conex.createStatement();
           st.executeUpdate("INSERT INTO estudiante VALUES ('" + CodEstud + "','" + Nombre + "','" + Apellido + "','" + Email + "','" + Sexo + "','" + Enfermedad + "','" + FechaNac + "','" + grupoSeleccionao.getIdGrupo() + "','" + Usuario + "','" + Contra + "')");
            JOptionPane.showMessageDialog(null, "Se ha realizado el registro de manera satisfactoria");
        } catch (SQLException ex) {
            Logger.getLogger(Registro_Profesor.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No es posible la conexión a la base de datos");
        }

    }//GEN-LAST:event_ComprobarActionPerformed

    private void apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Estudiante().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JTextField CodigoE;
    private javax.swing.JButton Comprobar;
    private javax.swing.JTextField ContraE;
    private javax.swing.JTextField Correo;
    private javax.swing.JRadioButton Diabetes;
    private javax.swing.ButtonGroup Enfermedad;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JComboBox<String> GrupoE;
    private javax.swing.JRadioButton Hipertension;
    private javax.swing.JButton Iniciar;
    private javax.swing.JRadioButton Latiroides;
    private javax.swing.JLabel Logo;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JButton Minimizar;
    private javax.swing.JRadioButton NoAplica;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JTextField UsuarioE;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
