/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author User
 */
public class Registro_Profesor extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    Connection conex;
    public Registro_Profesor() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            this.setTitle("Registro de profesor");
            botontransparente();
            textos();
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registro_Profesor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void textos(){
        TextPrompt a = new TextPrompt ("Escribe tu código",CodigoP);
        TextPrompt b = new TextPrompt ("1er nombre",nombre1);
        TextPrompt c = new TextPrompt ("2do nombre",nombre2);
        TextPrompt d = new TextPrompt ("1er apellido",apellido1);
        TextPrompt e = new TextPrompt ("2do apellido",apellido2);
        TextPrompt g = new TextPrompt ("Crea un usuario",UsuarioP);
        TextPrompt h= new TextPrompt ("Crea una contraseña",ContraP);
        TextPrompt i = new TextPrompt ("Digita tu correo electronico",Correo);
    }
    
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
       return retValue;
    }
    
    public void botontransparente(){
        Cerrar.setOpaque(false);
        Cerrar.setContentAreaFilled(false);
        Cerrar.setBorderPainted(false);
        Minimizar.setOpaque(false);
        Minimizar.setContentAreaFilled(false);
        Minimizar.setBorderPainted(false);
        nombre1.setBackground(new java.awt.Color (0,0,0,1));
        nombre2.setBackground(new java.awt.Color (0,0,0,1));
        apellido1.setBackground(new java.awt.Color (0,0,0,1));
        apellido2.setBackground(new java.awt.Color (0,0,0,1));
        Correo.setBackground(new java.awt.Color (0,0,0,1));
        fecha.setBackground(new java.awt.Color (0,0,0,1));
        CodigoP.setBackground(new java.awt.Color (0,0,0,1));
        UsuarioP.setBackground(new java.awt.Color (0,0,0,1));
        ContraP.setBackground(new java.awt.Color (0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enfermedad = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JButton();
        Minimizar = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        apellido1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        Femenino = new javax.swing.JRadioButton();
        Masculino = new javax.swing.JRadioButton();
        Correo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Latiroides = new javax.swing.JRadioButton();
        Diabetes = new javax.swing.JRadioButton();
        Hipertension = new javax.swing.JRadioButton();
        NoAplica = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        CodigoP = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        UsuarioP = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        ContraP = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Comprobar = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(1050, 575));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        Logo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoMouseMoved(evt);
            }
        });
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoMouseExited(evt);
            }
        });
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 12, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nombre.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel4.setText("Tu mejor sitio virtual para estudiar ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        jPanel1.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 40, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 43, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        jPanel2.setBackground(new java.awt.Color(218, 227, 243));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PROFESOR INGRESA TU...");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 33, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 90, 40, 40));

        nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre1.setBorder(null);
        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });
        jPanel2.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 100, 180, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 130, 220, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 90, 40, 40));

        nombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre2.setBorder(null);
        jPanel2.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 100, 180, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 130, 220, 20));

        apellido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apellido1.setBorder(null);
        jPanel2.add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 100, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 90, 40, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 130, 220, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 191, 40, 40));

        apellido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apellido2.setBorder(null);
        jPanel2.add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 201, 180, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 231, 220, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 191, 40, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Fecha de nacimiento:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 160, -1, -1));
        jPanel2.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 201, 180, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 231, 220, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Sexo:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        Sexo.add(Femenino);
        Femenino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Femenino.setText("Femenino");
        jPanel2.add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 206, -1, -1));

        Sexo.add(Masculino);
        Masculino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Masculino.setText("Masculino");
        jPanel2.add(Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 206, -1, -1));

        Correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Correo.setBorder(null);
        jPanel2.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 250, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/correo-electronico.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 40, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("¿Sufres alguna de estas enfermedades?");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuidado-de-la-salud.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        Enfermedad.add(Latiroides);
        Latiroides.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Latiroides.setText("Tiroides ");
        jPanel2.add(Latiroides, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        Enfermedad.add(Diabetes);
        Diabetes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Diabetes.setText("Diabetes");
        jPanel2.add(Diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        Enfermedad.add(Hipertension);
        Hipertension.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hipertension.setText("Hipertensión ");
        jPanel2.add(Hipertension, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        Enfermedad.add(NoAplica);
        NoAplica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NoAplica.setText("N/A");
        NoAplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoAplicaActionPerformed(evt);
            }
        });
        jPanel2.add(NoAplica, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contrasena.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        CodigoP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CodigoP.setBorder(null);
        CodigoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoPActionPerformed(evt);
            }
        });
        jPanel2.add(CodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 150, 30));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, 10));

        UsuarioP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsuarioP.setBorder(null);
        UsuarioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioPActionPerformed(evt);
            }
        });
        jPanel2.add(UsuarioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 160, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 40, 40));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 200, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrar-contrasena.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 40, 40));

        ContraP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ContraP.setBorder(null);
        ContraP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraPActionPerformed(evt);
            }
        });
        jPanel2.add(ContraP, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 170, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 200, 30));

        Comprobar.setBackground(new java.awt.Color(143, 170, 220));
        Comprobar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Comprobar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprobar.png"))); // NOI18N
        Comprobar.setText("COMPROBAR");
        Comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprobarActionPerformed(evt);
            }
        });
        jPanel2.add(Comprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        Iniciar.setBackground(new java.awt.Color(143, 170, 220));
        Iniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ordenador-portatil.png"))); // NOI18N
        Iniciar.setText("INICIAR SESIÓN");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        jPanel2.add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        scrollPane1.add(jPanel2);

        getContentPane().add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 730, 420));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro_total (1).png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1040, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarActionPerformed
        this.setState (Inicio.ICONIFIED);
    }//GEN-LAST:event_MinimizarActionPerformed

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        this.setVisible(false);
        Inicio v= new Inicio();
        v.setVisible(true);
    }//GEN-LAST:event_LogoMouseClicked

    private void LogoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseMoved
        Logo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_LogoMouseMoved

    private void LogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseExited
        Logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217,217,217)));
    }//GEN-LAST:event_LogoMouseExited

    private void ComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprobarActionPerformed

        if (nombre1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes poner un nombre");
        }
        
        if (apellido1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes poner un apellido");
        }
        
        if (fecha.getMaxSelectableDate().equals("")){
            JOptionPane.showMessageDialog(null,"Debes poner tu fecha de nacimiento");
        }
        
        if (CodigoP.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes poner tu código como profesor");
        }
        
        if (UsuarioP.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes crear un usuario");
        }
        
        if (ContraP.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes crear una contraseña");
        }

        String Nom1 = nombre1.getText();
        String Nom2 = nombre2.getText();
        String Ape1 = apellido1.getText();
        String Ape2 = apellido2.getText();

        String Nombre = Nom1+" "+Nom2;
        String Apellido = Ape1+" "+Ape2;


        int Anio = fecha.getCalendar().get(Calendar.YEAR);
        int Mes = fecha.getCalendar().get(Calendar.MONTH);
        int Dia = fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        
        Mes = Mes+1;

        String FechaNac = ""+Anio+"-"+Mes+"-"+Dia;

        String Enfermedad = null;

        if (Latiroides.isSelected()) {
            Enfermedad = "Tiroides";
        } if (Diabetes.isSelected()) {
            Enfermedad = "Diabetes";
        } if (Hipertension.isSelected()) {
            Enfermedad = "Hipertension";
        } if (NoAplica.isSelected()) {
            Enfermedad = "No_aplica";
        }

        String Email = Correo.getText();

        String Sexo = null;

        if (Femenino.isSelected()) {
            Sexo = "Femenino";
        } if (Masculino.isSelected()) {
            Sexo = "Masculino";
        }

        String Usuario = UsuarioP.getText();
        String Contra = ContraP.getText();

        String CodProfe = CodigoP.getText();

        try {
            conex = DriverManager.getConnection("jdbc:mysql://localhost/thats_study","root","" );
            Statement st = conex.createStatement();
            st.executeUpdate("INSERT INTO profesor VALUES ('"+CodProfe+"','"+Nombre+"','"+Apellido+"','"+Email+"','"+Sexo+"','"+Enfermedad+"','"+FechaNac+"','"+Usuario+"','"+Contra+"')");
        } catch (SQLException ex) {
            Logger.getLogger(Registro_Profesor.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No es posible la conexión a la base de datos");
        }
        JOptionPane.showMessageDialog(null, "Se ha realizado el registro de manera satisfactoria");
    }//GEN-LAST:event_ComprobarActionPerformed

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed

    }//GEN-LAST:event_nombre1ActionPerformed

    private void NoAplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoAplicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoAplicaActionPerformed

    private void CodigoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoPActionPerformed

    private void UsuarioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioPActionPerformed

    private void ContraPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraPActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        this.setVisible(false);
        Cuenta_profesor v= new Cuenta_profesor();
        v.setVisible(true);
    }//GEN-LAST:event_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Profesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JTextField CodigoP;
    private javax.swing.JButton Comprobar;
    private javax.swing.JTextField ContraP;
    private javax.swing.JTextField Correo;
    private javax.swing.JRadioButton Diabetes;
    private javax.swing.ButtonGroup Enfermedad;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JRadioButton Hipertension;
    private javax.swing.JButton Iniciar;
    private javax.swing.JRadioButton Latiroides;
    private javax.swing.JLabel Logo;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JButton Minimizar;
    private javax.swing.JRadioButton NoAplica;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JTextField UsuarioP;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
