/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author User
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        botontransparente();
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
       return retValue;
    }
    public void botontransparente(){
        Cerrar.setOpaque(false);
        Cerrar.setContentAreaFilled(false);
        Cerrar.setBorderPainted(false);
        Minimizar.setOpaque(false);
        Minimizar.setContentAreaFilled(false);
        Minimizar.setBorderPainted(false);
        nombre1.setBackground(new java.awt.Color (0,0,0,1));
        nombre2.setBackground(new java.awt.Color (0,0,0,1));
        apellido1.setBackground(new java.awt.Color (0,0,0,1));
        apellido2.setBackground(new java.awt.Color (0,0,0,1));
        Correo.setBackground(new java.awt.Color (0,0,0,1));
        fecha.setBackground(new java.awt.Color (0,0,0,1));
        Documento.setBackground(new java.awt.Color (0,0,0,1));
        Sig.setOpaque(false);
        Sig.setContentAreaFilled(false);
        Sig.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rol = new javax.swing.ButtonGroup();
        Enfermedad = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JButton();
        Minimizar = new javax.swing.JButton();
        apellido1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        apellido2 = new javax.swing.JTextField();
        Documento = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Estudiante = new javax.swing.JRadioButton();
        Profesor = new javax.swing.JRadioButton();
        Hipertension = new javax.swing.JRadioButton();
        Diabetes = new javax.swing.JRadioButton();
        Latiroides = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Masculino = new javax.swing.JRadioButton();
        Femenino = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Sig = new javax.swing.JButton();
        NoAplica = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(1050, 575));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        Logo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoMouseMoved(evt);
            }
        });
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nombre.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel4.setText("Tu mejor sitio virtual para estudiar ");

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cerrar)
                    .addComponent(Minimizar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 100));

        apellido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apellido1.setText("1er apellido");
        apellido1.setBorder(null);
        getContentPane().add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuidado-de-la-salud.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 40, 40));

        nombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre2.setText("2do nombre");
        nombre2.setBorder(null);
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 180, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 40, 40));

        nombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre1.setText("1er nombre");
        nombre1.setBorder(null);
        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 180, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 40, 40));

        Correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Correo.setText("Correo electronico ");
        Correo.setBorder(null);
        getContentPane().add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 280, 30));

        apellido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apellido2.setText("2do apellido");
        apellido2.setBorder(null);
        getContentPane().add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 180, 30));

        Documento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Documento.setText("No. Documento");
        Documento.setBorder(null);
        getContentPane().add(Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 180, 30));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 180, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/correo-electronico.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 40, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 40, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarjeta-de-credito.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 40, 40));

        Rol.add(Estudiante);
        Estudiante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Estudiante.setText("Estudiante");
        getContentPane().add(Estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 130, -1));

        Rol.add(Profesor);
        Profesor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Profesor.setText("Profesor");
        getContentPane().add(Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 130, -1));

        Enfermedad.add(Hipertension);
        Hipertension.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hipertension.setText("Hipertensión ");
        getContentPane().add(Hipertension, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 120, -1));

        Enfermedad.add(Diabetes);
        Diabetes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Diabetes.setText("Diabetes");
        getContentPane().add(Diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, -1, -1));

        Enfermedad.add(Latiroides);
        Latiroides.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Latiroides.setText("Latiroides ");
        getContentPane().add(Latiroides, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("enfermedades?");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        Sexo.add(Masculino);
        Masculino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Masculino.setText("Masculino");
        getContentPane().add(Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, -1, -1));

        Sexo.add(Femenino);
        Femenino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Femenino.setText("Femenino");
        getContentPane().add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 220, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 220, 20));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 220, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 220, 20));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 320, 20));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 220, 20));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 220, 20));

        Sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proximo.png"))); // NOI18N
        Sig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigMouseClicked(evt);
            }
        });
        Sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigActionPerformed(evt);
            }
        });
        getContentPane().add(Sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, -1, -1));

        Enfermedad.add(NoAplica);
        NoAplica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NoAplica.setText("N/A");
        NoAplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoAplicaActionPerformed(evt);
            }
        });
        getContentPane().add(NoAplica, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("¿Sufres alguna de estas");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarActionPerformed
        this.setState (Inicio.ICONIFIED);
    }//GEN-LAST:event_MinimizarActionPerformed

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        this.setVisible(false);
        Inicio v= new Inicio();
        v.setVisible(true);
    }//GEN-LAST:event_LogoMouseClicked

    private void LogoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseMoved
        Logo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_LogoMouseMoved

    private void LogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseExited
        Logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217,217,217)));
    }//GEN-LAST:event_LogoMouseExited

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed
        
    }//GEN-LAST:event_nombre1ActionPerformed

    private void SigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigActionPerformed
        String Nom1 = nombre1.getText();
        String Nom2 = nombre2.getText();
        String Ape1 = apellido1.getText();
        String Ape2 = apellido2.getText();
        
        
        int Anio = fecha.getCalendar().get(Calendar.YEAR);
        int Mes = fecha.getCalendar().get(Calendar.MONTH);
        int Dia = fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        
        
        String FechaNac = ""+Anio+"-"+Mes+"-"+Dia;
        
        
        String Enfermedad = null; 
        
        if (Latiroides.isSelected()) {
            Enfermedad = "Latiroides";
        } if (Diabetes.isSelected()) {
            Enfermedad = "Diabetes";
        } if (Hipertension.isSelected()) {
            Enfermedad = "Hipertensión";
        } if (NoAplica.isSelected()) {
            Enfermedad = "No aplica";
        }        
        
        
        String Id = Documento.getText();
        String Email = Correo.getText();
        
        
        String Sexo = null;
        
        if (Femenino.isSelected()) {
            Sexo = "Femenino";
        } if (Masculino.isSelected()) {
            Sexo = "Masculino";
        }
        
        
        String Rol = null;
        
        if (Profesor.isSelected()){
           Rol = "Profesor";
           this.setVisible(false);
           RegistroP v= new RegistroP();
           v.setVisible(true);
        } if (Estudiante.isSelected()){
           Rol = "Estudiante";
           this.setVisible(false);
           RegistroE v= new RegistroE();
           v.setVisible(true);
        }
    }//GEN-LAST:event_SigActionPerformed

    private void SigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigMouseClicked
        
    }//GEN-LAST:event_SigMouseClicked

    private void NoAplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoAplicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoAplicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JTextField Correo;
    private javax.swing.JRadioButton Diabetes;
    private javax.swing.JTextField Documento;
    private javax.swing.ButtonGroup Enfermedad;
    private javax.swing.JRadioButton Estudiante;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JRadioButton Hipertension;
    private javax.swing.JRadioButton Latiroides;
    private javax.swing.JLabel Logo;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JButton Minimizar;
    private javax.swing.JRadioButton NoAplica;
    private javax.swing.JRadioButton Profesor;
    private javax.swing.ButtonGroup Rol;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton Sig;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    // End of variables declaration//GEN-END:variables
}
