/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Image;
import java.awt.Toolkit;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author User
 */
public class RegistroE extends javax.swing.JFrame {

    /**
     * Creates new form RegistroE
     */
    public RegistroE() {
        initComponents();
        this.setLocationRelativeTo(null);
        transparente();
    }
    
    public void transparente(){
        Cerrar.setOpaque(false);
        Cerrar.setContentAreaFilled(false);
        Cerrar.setBorderPainted(false);
        Minimizar.setOpaque(false);
        Minimizar.setContentAreaFilled(false);
        Minimizar.setBorderPainted(false);
        GradoE.setBackground(new java.awt.Color (0,0,0,1));
        GrupoE.setBackground(new java.awt.Color (0,0,0,1));
        CodigoE.setBackground(new java.awt.Color (0,0,0,1));
        UsuarioE.setBackground(new java.awt.Color (0,0,0,1));
        ContraE.setBackground(new java.awt.Color (0,0,0,1));
    }
    
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
       return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoE = new javax.swing.JTextField();
        ColegioE = new javax.swing.JComboBox<>();
        CodigoE = new javax.swing.JTextField();
        ContraE = new javax.swing.JTextField();
        GradoE = new javax.swing.JTextField();
        UsuarioE = new javax.swing.JTextField();
        Iniciar = new javax.swing.JButton();
        Iniciar1 = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        Minimizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(1050, 575));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GrupoE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GrupoE.setText("Grupo");
        GrupoE.setBorder(null);
        GrupoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrupoEActionPerformed(evt);
            }
        });
        getContentPane().add(GrupoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 160, 30));

        ColegioE.setBackground(new java.awt.Color(143, 170, 220));
        ColegioE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ColegioE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comfandi Miraflores", "Comfandi el Prado", "Comfandi Calipso", "Comfandi Ciudadela", "Comfandi San Nicolas" }));
        getContentPane().add(ColegioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 170, 30));

        CodigoE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CodigoE.setText("Código de estudiante ");
        CodigoE.setBorder(null);
        CodigoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoEActionPerformed(evt);
            }
        });
        getContentPane().add(CodigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 150, 30));

        ContraE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ContraE.setText("Crea una contraseña");
        ContraE.setBorder(null);
        ContraE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraEActionPerformed(evt);
            }
        });
        getContentPane().add(ContraE, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 160, 30));

        GradoE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GradoE.setText("Grado");
        GradoE.setBorder(null);
        GradoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradoEActionPerformed(evt);
            }
        });
        getContentPane().add(GradoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 150, 30));

        UsuarioE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsuarioE.setText("Crea un usuario");
        UsuarioE.setBorder(null);
        UsuarioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioEActionPerformed(evt);
            }
        });
        getContentPane().add(UsuarioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 150, 30));

        Iniciar.setBackground(new java.awt.Color(143, 170, 220));
        Iniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprobar.png"))); // NOI18N
        Iniciar.setText("COMPROBAR");
        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, -1));

        Iniciar1.setBackground(new java.awt.Color(143, 170, 220));
        Iniciar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Iniciar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ordenador-portatil.png"))); // NOI18N
        Iniciar1.setText("INICIAR SESIÓN");
        Iniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, -1, -1));

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 40, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrar-contrasena.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contrasena.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 40, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/universidad.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 40, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 40, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 200, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 190, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 190, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 200, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 190, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroE.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodigoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoEActionPerformed

    private void ContraEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraEActionPerformed

    private void UsuarioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioEActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarActionPerformed
        this.setState (Inicio.ICONIFIED);
    }//GEN-LAST:event_MinimizarActionPerformed

    private void Iniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar1ActionPerformed
        this.setVisible(false);
        Cuenta v= new Cuenta();
        v.setVisible(true);
    }//GEN-LAST:event_Iniciar1ActionPerformed

    private void GradoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradoEActionPerformed

    private void GrupoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrupoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrupoEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JTextField CodigoE;
    private javax.swing.JComboBox<String> ColegioE;
    private javax.swing.JTextField ContraE;
    private javax.swing.JTextField GradoE;
    private javax.swing.JTextField GrupoE;
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton Iniciar1;
    private javax.swing.JButton Minimizar;
    private javax.swing.JTextField UsuarioE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
